### ISSUE TITLE
suggestion for making autocomplete work in your examples

### ISSUE THREAD

**Issue by rodgutierrez** [RPGillespie6/codemirror-quickstart#1]
thanks so much for putting this project together! it made it possible for me to get something working in a reasonable amount of time.

after I got something up and running locally, i noticed that autocomplete wasn't working as expected. i went back to the examples in this project and realized autocomplete wasn't working there either. i re-read [Example: Bundling with Rollup](https://codemirror.net/examples/bundle/) a couple times and finally noticed a subtle difference in our implementations.

for autocomplete to work, you'll want to update [this line](https://github.com/RPGillespie6/codemirror-quickstart/blob/master/src/editor.js#L12) in `editor.js` to be:

`import { javascript } from "@codemirror/lang-javascript"`

and then include `javascript()` in your extension list instead of `javascriptLanguage`.

cheers!

**Comment by RPGillespie6** [comment]
Thanks, glad you found it useful! Feel free to open a PR if you think it would help others and I'll merge it

**Comment by RPGillespie6** [comment]
This was a great suggestion, took me a while to come back around to this project to give it some love. Should be fixed now for future visitors.
