### ISSUE TITLE
Example 2: Toggling editor theme deletes edited text

### ISSUE THREAD

**Issue by jasonwirth** [RPGillespie6/codemirror-quickstart#2]
Enter some text, toggle to dark them, text is reset to initial state.

**Comment by RPGillespie6** [comment]
Ah, yeah, it's because you are creating a new state with the new theme. If you want to retain the text across theme changes, just pass in the current text when creating the new state:
```
let options = {
    oneDark: oneDarkEl.checked,
}

const new_state = cm6.createEditorState(view.state.doc, options);
view.setState(new_state)
```
